name: 'OBS Studio CI run'

on:
  push:
    branches: ['*']
  schedule:
    - cron: '19 13 * * *'
  workflow_dispatch:

jobs:
  linux_run:
    runs-on: 'ubuntu-22.04'
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout run-script'
        uses: actions/checkout@v3

      - name: 'Setup (0)'
        id: setup0
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha="$(gh api /repos/obsproject/obs-studio/commits | jq '.[0]["sha"]' | tr -d '"' | head -c 9)"
          echo "obsHashAPI=$sha" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: 'Restore obs-studio directory'
        id: obs-studio-cache
        if: github.event_name != 'schedule'
        uses: actions/cache/restore@v3
        with:
          path: obs-studio
          key: obs-studio-${{ steps.setup0.outputs.obsHashAPI }}
          restore-keys: obs-studio-

      - name: 'Checkout obs-studio'
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: 'obs-studio'
          submodules: 'recursive'
          fetch-depth: 0
          clean: false

      - name: 'Setup build environment'
        id: setup
        run: |
          (cd obs-studio && git pull && git submodule update --recursive)
          echo "obsHash=$(cd obs-studio && git rev-parse --short=9 HEAD)" >> $GITHUB_OUTPUT

      - name: 'Restore obs-build-dependencies directory'
        id: obs-build-dependencies-cache
        if: github.event_name != 'schedule'
        uses: actions/cache/restore@v3
        with:
          path: obs-build-dependencies
          key: obs-build-dependencies-${{ steps.setup.outputs.obsHash }}
          restore-keys: obs-build-dependencies-

      - name: 'Restore ccache'
        id: ccache-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: cirun-ccache-${{ steps.setup.outputs.obsHash }}
          restore-keys: cirun-ccache-

      - name: 'Configure and build obs-studio'
        run: |
          set -ex
          script/workflow2env.py -w obs-studio/.github/workflows/main.yml -j linux_build -e CEF_BUILD_VERSION_LINUX > build.env
          . build.env
          cd obs-studio
          patch -p1 < ../patch/cmake-coverage.patch
          export RESTORED_CEF=''
          bash -x CI/build-linux.sh

      - name: 'Save ccache'
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ github.workspace }}/.ccache
          key: cirun-ccache-${{ steps.setup.outputs.obsHash }}

      - name: 'Save obs-studio build directory'
        uses: actions/cache/save@v3
        if: ${{ steps.obs-studio-cache.outputs.cache-hit != 'true' }}
        with:
          path: obs-studio
          key: obs-studio-${{ steps.setup.outputs.obsHash }}

      - name: 'Restore obs-build-dependencies directory'
        uses: actions/cache/save@v3
        if: ${{ steps.obs-build-dependencies-cache.outputs.cache-hit != 'true' }}
        with:
          path: obs-build-dependencies
          key: obs-build-dependencies-${{ steps.setup.outputs.obsHash }}

      - name: 'Run unit tests'
        run: |
          cd obs-studio
          cmake -DENABLE_UNIT_TESTS=ON build/
          cmake --build build
          cmake --build build -t test

      - name: 'Install obs-studio and test suites'
        run: |
          set -e

          (cd obs-studio && sudo cmake --install build)

          apt_packages=(
            apt-transport-https gnupg
            xvfb
            x11-xserver-utils
            ffmpeg
            nginx libnginx-mod-rtmp
            python3-pip
            python3-pil
            python3-tk python3-dev
            python3-tesserocr
            scrot
            xdotool
            lcov
          )
          sudo apt install -y "${apt_packages[@]}"
          pip3 install -U -r cirun/requirements.txt

          curl -L https://notesalexp.org/debian/alexp_key.asc | sudo apt-key add -
          sudo tee -a /etc/apt/sources.list <<<"deb https://notesalexp.org/tesseract-ocr5/jammy/ jammy main"
          sudo apt update
          sudo apt install -y tesseract-ocr tesseract-ocr-eng

          git clone https://github.com/norihiro/untriseptium.git
          (cd untriseptium && pip3 install -U ./)

          sudo tee -a /etc/nginx/nginx.conf <<-EOF
          rtmp_auto_push on;
          rtmp {
            server {
              listen 1935;
              chunk_size 4096;
              timeout 10s;
              application live {
                live on;
                allow publish all;
              }
            }
          }
          EOF

      - name: 'Run just version and help'
        run: |
          obs --version
          obs --help

      - name: 'Run first time'
        run: |
          mkdir screenshot
          timeout 3m xvfb-run cirun/firsttime.py

      - name: 'Run second time'
        run: |
          sudo nginx &
          mkdir -p screenshot
          timeout 10m xvfb-run cirun/obs-secondtime.py

      - name: 'Start again and just exit'
        run: |
          timeout 3m xvfb-run timeout -s SIGINT --preserve-status -k 30 10 obs

      - name: 'Gather coverage data'
        if: always()
        run: |
          set -e
          cd obs-studio
          lcov \
            --exclude '/usr/*' \
            --exclude '*_autogen/*' \
            --exclude '${{ github.workspace }}/obs-build-dependencies/*' \
            --exclude '*/deps/*' \
            --exclude '*/ftl-sdk/*' \
            --exclude '*/decklink-sdk/*' \
            --exclude '*/libnsgif/*' \
            --exclude '*/obs-outputs/librtmp/*' \
            --exclude '*/rnnoise/src/*' \
            -q \
            -c -d . -o lcov.info
          genhtml -q lcov.info -o ../coverage/

      - name: 'Gather log files'
        if: always()
        run: |
          mv $HOME/.config/obs-studio/logs .
          mkdir -p recording
          mv $HOME/*.mp4 recording/ || true
          for i in desktop*.mkv; do
            ffmpeg -loglevel error -i $i -c copy recording/${i/.mkv/.mp4} || true
          done
          rsync -a --exclude obs-browser $HOME/.config/obs-studio/ config-obs-studio/

      - name: 'Upload log files'
        if: always()
        env:
          CIRUN_DEPLOY_SSHKEY: ${{ secrets.CIRUN_DEPLOY_SSHKEY }}
          CIRUN_DEPLOY_HOSTKEY: ${{ secrets.CIRUN_DEPLOY_HOSTKEY }}
          CIRUN_DEPLOY_TARGET: ${{ secrets.CIRUN_DEPLOY_TARGET }}
        run: |
          set +x
          mkdir -m 700 -p ~/.ssh
          echo "${CIRUN_DEPLOY_SSHKEY}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${CIRUN_DEPLOY_HOSTKEY}" | base64 -d >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          rsync -a logs config-obs-studio coverage screenshot recording "${CIRUN_DEPLOY_TARGET}"

      - name: 'Upload results'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: 'obs-studio-cirun-${{ steps.setup.outputs.obsHash }}'
          path: |
            screenshot/
            logs/
            coverage/

  macos_run:
    runs-on: 'macos-12'
    env:
      BLOCKED_FORMULAS: 'speexdsp curl php composer'
    defaults:
      run:
        shell: bash

    steps:
      - name: 'Checkout run-script'
        uses: actions/checkout@v3

      - name: 'Setup (0)'
        id: setup0
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha="$(gh api /repos/obsproject/obs-studio/commits | jq '.[0]["sha"]' | tr -d '"' | head -c 9)"
          patchhash=$(git log -1 --format='%h' patch/)
          echo "obsHashAPI=$sha" >> $GITHUB_OUTPUT
          echo "patchHash=$patchHash" >> $GITHUB_OUTPUT

      - name: 'Restore obs-studio directory'
        id: obs-studio-cache
        if: github.event_name != 'schedule'
        uses: actions/cache/restore@v3
        with:
          path: obs-studio
          key: obs-studio-macos-${{ steps.setup0.outputs.obsHashAPI }}-${{ steps.setup0.outputs.patchHash }}
          restore-keys: obs-studio-macos-

      - name: 'Checkout obs-studio'
        if: ${{ steps.obs-studio-cache.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: 'obs-studio'
          submodules: 'recursive'
          fetch-depth: 0
          clean: false

      - name: 'Setup build environment'
        id: setup
        run: |
          echo "obsHash=$(cd obs-studio && git rev-parse --short=9 HEAD)" >> $GITHUB_OUTPUT

      - name: 'Restore ccache from cache'
        id: ccache-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ steps.setup.outputs.obsHash }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: 'Build OBS'
        if: ${{ steps.obs-studio-cache.outputs.cache-hit != 'true' }}
        run: |
          REMOVE_FORMULAS=""
          for FORMULA in ${{ env.BLOCKED_FORMULAS }}; do
            if [ -d "/usr/local/opt/${FORMULA}" ]; then
              REMOVE_FORMULAS="${REMOVE_FORMULAS} ${FORMULA}"
            fi
          done
          if [ -n "${REMOVE_FORMULAS}" ]; then
            brew uninstall ${REMOVE_FORMULAS}
          fi

          cd obs-studio
          patch -p1 < ../patch/cmake-coverage.patch
          rm -rf build_x86_64/OBS.app
          export -n SEEKING_TESTERS
          export TERM=''
          export -n CI
          export -n GITHUB_RUN_ID
          CI/macos/01_install_dependencies.sh --architecture x86_64
          CI/macos/02_build_obs.sh --architecture x86_64

      - name: 'Save ccache'
        if: always()
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ steps.setup.outputs.obsHash }}

      - name: 'Save obs-studio build directory'
        uses: actions/cache/save@v3
        if: ${{ steps.obs-studio-cache.outputs.cache-hit != 'true' }}
        with:
          path: obs-studio
          key: obs-studio-macos-${{ steps.setup.outputs.obsHash }}-${{ steps.setup0.outputs.patchHash }}

      - name: 'Prepare desktop'
        uses: paulz/prepare-macos@v1

      - name: 'Prepare tools'
        run: |
          brew install tesseract
          pip3 install -U -r cirun/requirements.txt
          pip3 install -U Pillow
          git clone https://github.com/norihiro/untriseptium.git
          (cd untriseptium && pip3 install -U ./)

      - name: 'Run first time'
        run: |
          set +e
          python3 cirun/firsttime.py

          sleep 2
          killall -SIGINT OBS
          mv $HOME/'Library/Application Support/obs-studio/logs' .
          exit 0

      - name: 'Gather coverage data'
        if: always()
        run: |
          set -e
          cd obs-studio
          brew install lcov
          lcov \
            --exclude '/Applications/*' \
            --exclude '/usr/local/*' \
            --exclude '*/.deps/*' \
            --exclude '*_autogen/*' \
            --exclude '*/deps/*' \
            --exclude '*/ftl-sdk/*' \
            --exclude '*/decklink-sdk/*' \
            --exclude '*/libnsgif/*' \
            --exclude '*/obs-outputs/librtmp/*' \
            --exclude '*/rnnoise/src/*' \
            -q \
            -c -d . -o ../lcov.info
          genhtml -q ../lcov.info -o ../coverage/

      - name: 'Upload log files'
        if: always()
        env:
          CIRUN_DEPLOY_SSHKEY: ${{ secrets.CIRUN_DEPLOY_SSHKEY }}
          CIRUN_DEPLOY_HOSTKEY: ${{ secrets.CIRUN_DEPLOY_HOSTKEY }}
          CIRUN_DEPLOY_TARGET: ${{ secrets.CIRUN_DEPLOY_TARGET }}
        run: |
          set +x
          mkdir -m 700 -p ~/.ssh
          echo "${CIRUN_DEPLOY_SSHKEY}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${CIRUN_DEPLOY_HOSTKEY}" | base64 -d >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          rsync -a logs screenshot lcov.info coverage "${CIRUN_DEPLOY_TARGET}/macos/"

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: 'obs-studio-cirun-macos-${{ steps.setup.outputs.obsHash }}'
          path: |
            a.png
            logs/
